[.lead]
This project shows how to build "micro" applications with Spring Cloud Function. There is a library which an app should include in its dependencies, and which contains a sub-class of `SpringApplication` from Spring Boot, which should be used to launch the application. The main application class can be either a `Function` (with explicit input and output types and a default constructor), or else it needs to be an `ApplicationContextInitializer<GenericApplicationContext>` that registers functions as beans of type `FunctionRegistration`.

== Building the Apps

Build the jar:

```
$ ./mvnw clean install
```

Run it

```
$ java -jar sample/json/target/micro-sample-0.0.1-SNAPSHOT.jar 
...
2018-05-23 10:03:41.776 [main] INFO  com.example.DemoApplication - Started DemoApplication in 1.885 seconds (JVM running for 3.769)
...
```

== Building a Native Image

The `DemoApplication` ought to be convertible to a native binary image using the Graal tools. There is a `Dockerfile` that should be able to do this:

```
$ docker build -t demo/demo .
$ docker run -p 8080:8080 demo/demo
...
BeanInfo: com.example.func.ReactorConfiguration
2018-10-11 10:33:20.929  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 8080
2018-10-11 10:33:20.929  INFO 1 --- [           main] com.example.DemoApplication              : Started DemoApplication in 0.015 seconds (JVM running for 0.016)
2018-10-11 10:33:20.929  INFO 1 --- [           main] c.e.c.BeanCountingApplicationListener    : Bean count: application=53
```

Then test it:

```
$ curl localhost:8080 -H "Content-Type: application/json" -d '{"value":"foo"}' -w '\n'
{"value":"FOO"}
```

The docker build is parameterized with the sample name, so `docker build --build-arg SAMPLE=plain ....` or `docker build --build-arg SAMPLE=json ...` should work (the default is "json").

You can copy the native image out of the docker image if you want to run it (on Linux):

```
$ docker run --entrypoint cat demo/demo demo > demo
$ chmod +x demo
$ ./demo
...
BeanInfo: com.example.func.ReactorConfiguration
2018-10-11 10:33:20.929  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 8080
2018-10-11 10:33:20.929  INFO 1 --- [           main] com.example.DemoApplication              : Started DemoApplication in 0.015 seconds (JVM running for 0.016)
2018-10-11 10:33:20.929  INFO 1 --- [           main] c.e.c.BeanCountingApplicationListener    : Bean count: application=53
```


To do the same thing manually (without docker) first download https://github.com/oracle/graal/releases[GraalVM] and install it (add the bin dir to you path and set the `JAVA_HOME` to point to GraalVM). You can also use https://sdkman.io/[sdkman] to download it. You will need GraalVM 1.0.0-rc7 or later.

Compute the classpath using the `graal` profile so that we don't crash on missing classes:

```
$ cd samples/json
$ CP=`java -jar target/micro-sample-0.0.1-SNAPSHOT.jar --thin.classpath --thin.profile=graal`
```

Then build an image:

```
$ native-image -J-javaagent:/${HOME}/.m2/repository/org/aspectj/aspectjweaver/1.9.1/aspectjweaver-1.9.1.jar -Dio.netty.noUnsafe=true -Dio.netty.noJdkZlibDecoder=true -Dio.netty.noJdkZlibEncoder=true -H:Name=target/demo -H:ReflectionConfigurationFiles=`echo *.json | tr ' ' ,` -H:ReflectionConfigurationResources=META-INF/micro-library.json -H:IncludeResources='META-INF/.*.json|META-INF/spring.factories|org/springframework/boot/logging/.*' --delay-class-initialization-to-runtime=io.netty.handler.codec.http.HttpObjectEncoder,org.springframework.core.io.VfsUtils,io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator,io.netty.handler.ssl.ReferenceCountedOpenSslEngine  --report-unsupported-elements-at-runtime -cp $CP com.example.DemoApplication
$ ./target/demo

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                        

Aug 07, 2018 11:25:13 AM org.springframework.boot.StartupInfoLogger logStarting
INFO: Starting application on tower with PID 11253 (started by dsyer in /home/dsyer/dev/demo/workspace/micro)
Aug 07, 2018 11:25:13 AM org.springframework.boot.SpringApplication logStartupProfileInfo
INFO: No active profile set, falling back to default profiles: default
Aug 07, 2018 11:25:13 AM org.springframework.boot.web.embedded.netty.NettyWebServer start
INFO: Netty started on port(s): 8080
Aug 07, 2018 11:25:13 AM org.springframework.boot.StartupInfoLogger logStarted
INFO: Started application in 0.036 seconds (JVM running for 0.04)
Benchmark app started
Started HttpServer: 40ms
```

